# Generated by Django 2.1.1 on 2018-09-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('artist', models.CharField(max_length=128)),
                ('album', models.CharField(max_length=128)),
                ('album_index', models.IntegerField()),
                ('service', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('artwork', models.URLField()),
            ],
        ),
    ]
