# Generated by Django 2.1.1 on 2018-09-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20180921_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_cover_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artwork',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
