# Generated by Django 2.1.1 on 2018-10-13 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_auto_20181003_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album_index',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artwork',
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='songs.Album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='songs.Artist'),
        ),
    ]
