# Generated by Django 2.1.1 on 2018-10-13 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_service_refresh_token'),
        ('songs', '0006_auto_20181013_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='songs.Album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='songs.Artist'),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('name', 'artist', 'album', 'service')},
        ),
    ]
