# Generated by Django 2.1.1 on 2018-10-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_auto_20181013_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
