# Generated by Django 2.1.1 on 2018-10-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0011_song_s3_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='unique_id',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
