# Generated by Django 2.1.1 on 2018-10-22 04:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0014_song_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='users',
        ),
        migrations.AddField(
            model_name='song',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
