# Generated by Django 2.1.1 on 2018-10-22 06:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0016_auto_20181022_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
