# Generated by Django 2.1.1 on 2018-10-09 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_service',
            name='expire',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
