# Generated by Django 2.1.1 on 2018-10-09 06:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_user_service_expire'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_service',
            unique_together={('user_id', 'service_id')},
        ),
    ]
