# Generated by Django 2.1.1 on 2018-10-09 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181009_0622'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_service',
            unique_together=set(),
        ),
    ]
