# Generated by Django 2.1.1 on 2018-10-12 04:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181009_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_service',
            name='refresh_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
